name: Deploy to EKS

on:
  push:
    branches:
      - main   # runs when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.15'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name innovatemart-bedrock-eks --region us-east-1

      - name: Deploy Kubernetes manifests
        run: kubectl apply -f k8s-configs/
